import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    width: "100%",
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: "#8B4513",
    letterSpacing: 0.5,
  },
  backButton: {
    backgroundColor: "rgba(139, 69, 19, 0.1)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  backText: {
    color: "#8B4513",
    fontSize: 16,
    fontWeight: "600",
  },
  placeholder: {
    width: 60,
  },
  infoButtonContainer: {
    alignItems: "flex-end",
    marginBottom: 10,
  },
  infoButton: {
    backgroundColor: "rgba(139, 69, 19, 0.1)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  infoButtonText: {
    color: "#8B4513",
    fontSize: 14,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    width: "90%",
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E8D5B7",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#8B4513",
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#F5E6D3",
    justifyContent: "center",
    alignItems: "center",
  },
  closeButtonText: {
    fontSize: 18,
    color: "#8B4513",
    fontWeight: "bold",
  },
  chartContainer: {
    marginBottom: 24,
    padding: 16,
    backgroundColor: "#FDF8F2",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F0E0D0",
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#8B4513",
    textAlign: "center",
    marginBottom: 12,
  },
  statsRow: {
    marginTop: 12,
    alignItems: "center",
    gap: 4,
  },
  correctText: {
    fontSize: 14,
    color: "#4CAF50",
    fontWeight: "600",
  },
  incorrectText: {
    fontSize: 14,
    color: "#FF6B6B",
    fontWeight: "600",
  },
  totalText: {
    fontSize: 14,
    color: "#333",
    fontWeight: "600",
  },
  noDataText: {
    textAlign: "center",
    color: "#999",
    fontSize: 14,
    padding: 20,
  },
  questionCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  questionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  levelBadge: {
    backgroundColor: "#F5E6D3",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  levelText: {
    color: "#8B4513",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  techniqueText: {
    color: "#A0522D",
    fontSize: 14,
    fontWeight: "500",
    fontStyle: "italic",
  },
  descriptionText: {
    fontSize: 16,
    color: "#2C1810",
    lineHeight: 24,
    marginBottom: 24,
    fontWeight: "500",
  },
  equationContainer: {
    borderRadius: 16,
    padding: 24,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F0E0D0",
  },
  answerCard: {
    backgroundColor: "rgba(255, 255, 255, 0.97)",
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#8B4513",
    marginBottom: 16,
  },
  mathInput: {
    borderWidth: 2,
    borderColor: "#E8D5B7",
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    fontFamily: "monospace",
    backgroundColor: "#FFFFFF",
    marginBottom: 20,
    color: "#2C1810",
    minHeight: 100,
    textAlignVertical: "top",
  },
  previewContainer: {
    marginBottom: 20,
  },
  previewLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#8B4513",
    marginBottom: 8,
  },
  katexContainer: {
    backgroundColor: "#FDF8F2",
    borderRadius: 12,
    padding: 16,
    minHeight: 80,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F0E0D0",
  },
  answerDisplayContainer: {
    marginBottom: 20,
    padding: 16,
    backgroundColor: "#F0F9F0",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#C8E6C9",
  },
  answerDisplayLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2E7D32",
    marginBottom: 12,
  },
  answerDisplayBox: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  buttonGroup: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
  },
  button: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  checkButton: {
    backgroundColor: "#4CAF50",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  nextButton: {
    backgroundColor: "#8B4513",
    shadowColor: "#8B4513",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 12,
  },
  previousButton: {
    backgroundColor: "#6d6d6d",
    shadowColor: "#6d6d6d",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  disabledButton: {
    opacity: 0.5,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
  },
  customKeyboardContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#E8D5B7",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  keyboardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E8D5B7",
    backgroundColor: "#F5E6D3",
  },
  switchButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#8B4513",
    borderRadius: 8,
  },
  switchButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  dismissButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#8B4513",
    borderRadius: 8,
  },
  dismissText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
});